// Code generated by ogen, DO NOT EDIT.

package client

import (
	"io"
	"net/url"
)

// Ref: #/components/schemas/AdType
type AdType struct {
	Height OptInt32     `json:"Height"`
	ID     OptNilInt32  `json:"Id"`
	Name   OptNilString `json:"Name"`
	Width  OptInt32     `json:"Width"`
}

// GetHeight returns the value of Height.
func (s *AdType) GetHeight() OptInt32 {
	return s.Height
}

// GetID returns the value of ID.
func (s *AdType) GetID() OptNilInt32 {
	return s.ID
}

// GetName returns the value of Name.
func (s *AdType) GetName() OptNilString {
	return s.Name
}

// GetWidth returns the value of Width.
func (s *AdType) GetWidth() OptInt32 {
	return s.Width
}

// SetHeight sets the value of Height.
func (s *AdType) SetHeight(val OptInt32) {
	s.Height = val
}

// SetID sets the value of ID.
func (s *AdType) SetID(val OptNilInt32) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *AdType) SetName(val OptNilString) {
	s.Name = val
}

// SetWidth sets the value of Width.
func (s *AdType) SetWidth(val OptInt32) {
	s.Width = val
}

// Ref: #/components/schemas/AdTypeList
type AdTypeList struct {
	Items      []AdType `json:"items"`
	Page       OptInt32 `json:"page"`
	PageSize   OptInt32 `json:"pageSize"`
	TotalItems OptInt64 `json:"totalItems"`
	TotalPages OptInt32 `json:"totalPages"`
}

// GetItems returns the value of Items.
func (s *AdTypeList) GetItems() []AdType {
	return s.Items
}

// GetPage returns the value of Page.
func (s *AdTypeList) GetPage() OptInt32 {
	return s.Page
}

// GetPageSize returns the value of PageSize.
func (s *AdTypeList) GetPageSize() OptInt32 {
	return s.PageSize
}

// GetTotalItems returns the value of TotalItems.
func (s *AdTypeList) GetTotalItems() OptInt64 {
	return s.TotalItems
}

// GetTotalPages returns the value of TotalPages.
func (s *AdTypeList) GetTotalPages() OptInt32 {
	return s.TotalPages
}

// SetItems sets the value of Items.
func (s *AdTypeList) SetItems(val []AdType) {
	s.Items = val
}

// SetPage sets the value of Page.
func (s *AdTypeList) SetPage(val OptInt32) {
	s.Page = val
}

// SetPageSize sets the value of PageSize.
func (s *AdTypeList) SetPageSize(val OptInt32) {
	s.PageSize = val
}

// SetTotalItems sets the value of TotalItems.
func (s *AdTypeList) SetTotalItems(val OptInt64) {
	s.TotalItems = val
}

// SetTotalPages sets the value of TotalPages.
func (s *AdTypeList) SetTotalPages(val OptInt32) {
	s.TotalPages = val
}

type ApiKeyAuth struct {
	APIKey string
}

// GetAPIKey returns the value of APIKey.
func (s *ApiKeyAuth) GetAPIKey() string {
	return s.APIKey
}

// SetAPIKey sets the value of APIKey.
func (s *ApiKeyAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// Ref: #/components/schemas/Channel
type Channel struct {
	AdTypes []int32    `json:"AdTypes"`
	CPM     OptFloat32 `json:"CPM"`
	// Deprecated: schema marks this property as deprecated.
	Commission OptNilFloat32 `json:"Commission"`
	// Deprecated: schema marks this property as deprecated.
	CustomTargeting OptNilString `json:"CustomTargeting"`
	Engine          OptNilString `json:"Engine"`
	ID              OptNilInt32  `json:"Id"`
	IsDeleted       OptNilBool   `json:"IsDeleted"`
	// Deprecated: schema marks this property as deprecated.
	Keywords OptNilString `json:"Keywords"`
	Title    OptString    `json:"Title"`
}

// GetAdTypes returns the value of AdTypes.
func (s *Channel) GetAdTypes() []int32 {
	return s.AdTypes
}

// GetCPM returns the value of CPM.
func (s *Channel) GetCPM() OptFloat32 {
	return s.CPM
}

// GetCommission returns the value of Commission.
func (s *Channel) GetCommission() OptNilFloat32 {
	return s.Commission
}

// GetCustomTargeting returns the value of CustomTargeting.
func (s *Channel) GetCustomTargeting() OptNilString {
	return s.CustomTargeting
}

// GetEngine returns the value of Engine.
func (s *Channel) GetEngine() OptNilString {
	return s.Engine
}

// GetID returns the value of ID.
func (s *Channel) GetID() OptNilInt32 {
	return s.ID
}

// GetIsDeleted returns the value of IsDeleted.
func (s *Channel) GetIsDeleted() OptNilBool {
	return s.IsDeleted
}

// GetKeywords returns the value of Keywords.
func (s *Channel) GetKeywords() OptNilString {
	return s.Keywords
}

// GetTitle returns the value of Title.
func (s *Channel) GetTitle() OptString {
	return s.Title
}

// SetAdTypes sets the value of AdTypes.
func (s *Channel) SetAdTypes(val []int32) {
	s.AdTypes = val
}

// SetCPM sets the value of CPM.
func (s *Channel) SetCPM(val OptFloat32) {
	s.CPM = val
}

// SetCommission sets the value of Commission.
func (s *Channel) SetCommission(val OptNilFloat32) {
	s.Commission = val
}

// SetCustomTargeting sets the value of CustomTargeting.
func (s *Channel) SetCustomTargeting(val OptNilString) {
	s.CustomTargeting = val
}

// SetEngine sets the value of Engine.
func (s *Channel) SetEngine(val OptNilString) {
	s.Engine = val
}

// SetID sets the value of ID.
func (s *Channel) SetID(val OptNilInt32) {
	s.ID = val
}

// SetIsDeleted sets the value of IsDeleted.
func (s *Channel) SetIsDeleted(val OptNilBool) {
	s.IsDeleted = val
}

// SetKeywords sets the value of Keywords.
func (s *Channel) SetKeywords(val OptNilString) {
	s.Keywords = val
}

// SetTitle sets the value of Title.
func (s *Channel) SetTitle(val OptString) {
	s.Title = val
}

// Ref: #/components/schemas/ChannelList
type ChannelList struct {
	ChannelIds []int32 `json:"ChannelIds"`
}

// GetChannelIds returns the value of ChannelIds.
func (s *ChannelList) GetChannelIds() []int32 {
	return s.ChannelIds
}

// SetChannelIds sets the value of ChannelIds.
func (s *ChannelList) SetChannelIds(val []int32) {
	s.ChannelIds = val
}

// Ref: #/components/schemas/ChannelSiteMap
type ChannelSiteMap struct {
	ChannelId OptInt32 `json:"ChannelId"`
	// Deprecated: schema marks this property as deprecated.
	FixedPaymentAmount OptNilFloat32 `json:"FixedPaymentAmount"`
	Priority           OptNilInt32   `json:"Priority"`
	SiteId             OptInt32      `json:"SiteId"`
}

// GetChannelId returns the value of ChannelId.
func (s *ChannelSiteMap) GetChannelId() OptInt32 {
	return s.ChannelId
}

// GetFixedPaymentAmount returns the value of FixedPaymentAmount.
func (s *ChannelSiteMap) GetFixedPaymentAmount() OptNilFloat32 {
	return s.FixedPaymentAmount
}

// GetPriority returns the value of Priority.
func (s *ChannelSiteMap) GetPriority() OptNilInt32 {
	return s.Priority
}

// GetSiteId returns the value of SiteId.
func (s *ChannelSiteMap) GetSiteId() OptInt32 {
	return s.SiteId
}

// SetChannelId sets the value of ChannelId.
func (s *ChannelSiteMap) SetChannelId(val OptInt32) {
	s.ChannelId = val
}

// SetFixedPaymentAmount sets the value of FixedPaymentAmount.
func (s *ChannelSiteMap) SetFixedPaymentAmount(val OptNilFloat32) {
	s.FixedPaymentAmount = val
}

// SetPriority sets the value of Priority.
func (s *ChannelSiteMap) SetPriority(val OptNilInt32) {
	s.Priority = val
}

// SetSiteId sets the value of SiteId.
func (s *ChannelSiteMap) SetSiteId(val OptInt32) {
	s.SiteId = val
}

// Ref: #/components/schemas/ChannelSiteMapList
type ChannelSiteMapList struct {
	Items      []ChannelSiteMap `json:"items"`
	Page       OptInt32         `json:"page"`
	PageSize   OptInt32         `json:"pageSize"`
	TotalItems OptInt64         `json:"totalItems"`
	TotalPages OptInt32         `json:"totalPages"`
}

// GetItems returns the value of Items.
func (s *ChannelSiteMapList) GetItems() []ChannelSiteMap {
	return s.Items
}

// GetPage returns the value of Page.
func (s *ChannelSiteMapList) GetPage() OptInt32 {
	return s.Page
}

// GetPageSize returns the value of PageSize.
func (s *ChannelSiteMapList) GetPageSize() OptInt32 {
	return s.PageSize
}

// GetTotalItems returns the value of TotalItems.
func (s *ChannelSiteMapList) GetTotalItems() OptInt64 {
	return s.TotalItems
}

// GetTotalPages returns the value of TotalPages.
func (s *ChannelSiteMapList) GetTotalPages() OptInt32 {
	return s.TotalPages
}

// SetItems sets the value of Items.
func (s *ChannelSiteMapList) SetItems(val []ChannelSiteMap) {
	s.Items = val
}

// SetPage sets the value of Page.
func (s *ChannelSiteMapList) SetPage(val OptInt32) {
	s.Page = val
}

// SetPageSize sets the value of PageSize.
func (s *ChannelSiteMapList) SetPageSize(val OptInt32) {
	s.PageSize = val
}

// SetTotalItems sets the value of TotalItems.
func (s *ChannelSiteMapList) SetTotalItems(val OptInt64) {
	s.TotalItems = val
}

// SetTotalPages sets the value of TotalPages.
func (s *ChannelSiteMapList) SetTotalPages(val OptInt32) {
	s.TotalPages = val
}

type CreateAdTypeReq struct {
	Height int32     `json:"Height"`
	Name   OptString `json:"Name"`
	Width  int32     `json:"Width"`
}

// GetHeight returns the value of Height.
func (s *CreateAdTypeReq) GetHeight() int32 {
	return s.Height
}

// GetName returns the value of Name.
func (s *CreateAdTypeReq) GetName() OptString {
	return s.Name
}

// GetWidth returns the value of Width.
func (s *CreateAdTypeReq) GetWidth() int32 {
	return s.Width
}

// SetHeight sets the value of Height.
func (s *CreateAdTypeReq) SetHeight(val int32) {
	s.Height = val
}

// SetName sets the value of Name.
func (s *CreateAdTypeReq) SetName(val OptString) {
	s.Name = val
}

// SetWidth sets the value of Width.
func (s *CreateAdTypeReq) SetWidth(val int32) {
	s.Width = val
}

type CreateChannelReq struct {
	AdTypes   []int32       `json:"AdTypes"`
	CPM       OptNilFloat32 `json:"CPM"`
	Engine    int32         `json:"Engine"`
	IsDeleted OptBool       `json:"IsDeleted"`
	Title     string        `json:"Title"`
}

// GetAdTypes returns the value of AdTypes.
func (s *CreateChannelReq) GetAdTypes() []int32 {
	return s.AdTypes
}

// GetCPM returns the value of CPM.
func (s *CreateChannelReq) GetCPM() OptNilFloat32 {
	return s.CPM
}

// GetEngine returns the value of Engine.
func (s *CreateChannelReq) GetEngine() int32 {
	return s.Engine
}

// GetIsDeleted returns the value of IsDeleted.
func (s *CreateChannelReq) GetIsDeleted() OptBool {
	return s.IsDeleted
}

// GetTitle returns the value of Title.
func (s *CreateChannelReq) GetTitle() string {
	return s.Title
}

// SetAdTypes sets the value of AdTypes.
func (s *CreateChannelReq) SetAdTypes(val []int32) {
	s.AdTypes = val
}

// SetCPM sets the value of CPM.
func (s *CreateChannelReq) SetCPM(val OptNilFloat32) {
	s.CPM = val
}

// SetEngine sets the value of Engine.
func (s *CreateChannelReq) SetEngine(val int32) {
	s.Engine = val
}

// SetIsDeleted sets the value of IsDeleted.
func (s *CreateChannelReq) SetIsDeleted(val OptBool) {
	s.IsDeleted = val
}

// SetTitle sets the value of Title.
func (s *CreateChannelReq) SetTitle(val string) {
	s.Title = val
}

type CreateChannelSiteMapReq struct {
	ChannelId int32    `json:"channelId"`
	Priority  OptInt32 `json:"priority"`
	SiteId    int32    `json:"siteId"`
}

// GetChannelId returns the value of ChannelId.
func (s *CreateChannelSiteMapReq) GetChannelId() int32 {
	return s.ChannelId
}

// GetPriority returns the value of Priority.
func (s *CreateChannelSiteMapReq) GetPriority() OptInt32 {
	return s.Priority
}

// GetSiteId returns the value of SiteId.
func (s *CreateChannelSiteMapReq) GetSiteId() int32 {
	return s.SiteId
}

// SetChannelId sets the value of ChannelId.
func (s *CreateChannelSiteMapReq) SetChannelId(val int32) {
	s.ChannelId = val
}

// SetPriority sets the value of Priority.
func (s *CreateChannelSiteMapReq) SetPriority(val OptInt32) {
	s.Priority = val
}

// SetSiteId sets the value of SiteId.
func (s *CreateChannelSiteMapReq) SetSiteId(val int32) {
	s.SiteId = val
}

type CreateForChannelAdTypeReq struct {
	Height int32     `json:"Height"`
	Name   OptString `json:"Name"`
	Width  int32     `json:"Width"`
}

// GetHeight returns the value of Height.
func (s *CreateForChannelAdTypeReq) GetHeight() int32 {
	return s.Height
}

// GetName returns the value of Name.
func (s *CreateForChannelAdTypeReq) GetName() OptString {
	return s.Name
}

// GetWidth returns the value of Width.
func (s *CreateForChannelAdTypeReq) GetWidth() int32 {
	return s.Width
}

// SetHeight sets the value of Height.
func (s *CreateForChannelAdTypeReq) SetHeight(val int32) {
	s.Height = val
}

// SetName sets the value of Name.
func (s *CreateForChannelAdTypeReq) SetName(val OptString) {
	s.Name = val
}

// SetWidth sets the value of Width.
func (s *CreateForChannelAdTypeReq) SetWidth(val int32) {
	s.Width = val
}

type CreateSiteReq struct {
	IsDeleted     OptNilBool    `json:"IsDeleted"`
	NetworkMargin OptNilFloat32 `json:"NetworkMargin"`
	Title         string        `json:"Title"`
	URL           url.URL       `json:"URL"`
}

// GetIsDeleted returns the value of IsDeleted.
func (s *CreateSiteReq) GetIsDeleted() OptNilBool {
	return s.IsDeleted
}

// GetNetworkMargin returns the value of NetworkMargin.
func (s *CreateSiteReq) GetNetworkMargin() OptNilFloat32 {
	return s.NetworkMargin
}

// GetTitle returns the value of Title.
func (s *CreateSiteReq) GetTitle() string {
	return s.Title
}

// GetURL returns the value of URL.
func (s *CreateSiteReq) GetURL() url.URL {
	return s.URL
}

// SetIsDeleted sets the value of IsDeleted.
func (s *CreateSiteReq) SetIsDeleted(val OptNilBool) {
	s.IsDeleted = val
}

// SetNetworkMargin sets the value of NetworkMargin.
func (s *CreateSiteReq) SetNetworkMargin(val OptNilFloat32) {
	s.NetworkMargin = val
}

// SetTitle sets the value of Title.
func (s *CreateSiteReq) SetTitle(val string) {
	s.Title = val
}

// SetURL sets the value of URL.
func (s *CreateSiteReq) SetURL(val url.URL) {
	s.URL = val
}

type CreateZoneReq struct {
	IsDeleted OptNilBool  `json:"IsDeleted"`
	Name      string      `json:"Name"`
	SiteId    OptNilInt32 `json:"SiteId"`
}

// GetIsDeleted returns the value of IsDeleted.
func (s *CreateZoneReq) GetIsDeleted() OptNilBool {
	return s.IsDeleted
}

// GetName returns the value of Name.
func (s *CreateZoneReq) GetName() string {
	return s.Name
}

// GetSiteId returns the value of SiteId.
func (s *CreateZoneReq) GetSiteId() OptNilInt32 {
	return s.SiteId
}

// SetIsDeleted sets the value of IsDeleted.
func (s *CreateZoneReq) SetIsDeleted(val OptNilBool) {
	s.IsDeleted = val
}

// SetName sets the value of Name.
func (s *CreateZoneReq) SetName(val string) {
	s.Name = val
}

// SetSiteId sets the value of SiteId.
func (s *CreateZoneReq) SetSiteId(val OptNilInt32) {
	s.SiteId = val
}

// DeleteAdTypeOK is response for DeleteAdType operation.
type DeleteAdTypeOK struct{}

// DeleteChannelOK is response for DeleteChannel operation.
type DeleteChannelOK struct{}

// DeleteChannelSiteMapOK is response for DeleteChannelSiteMap operation.
type DeleteChannelSiteMapOK struct{}

// DeleteForChannelAdTypeOK is response for DeleteForChannelAdType operation.
type DeleteForChannelAdTypeOK struct{}

type FilterSiteOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s FilterSiteOK) Read(p []byte) (n int, err error) {
	return s.Data.Read(p)
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateAdTypeReq returns new OptCreateAdTypeReq with value set to v.
func NewOptCreateAdTypeReq(v CreateAdTypeReq) OptCreateAdTypeReq {
	return OptCreateAdTypeReq{
		Value: v,
		Set:   true,
	}
}

// OptCreateAdTypeReq is optional CreateAdTypeReq.
type OptCreateAdTypeReq struct {
	Value CreateAdTypeReq
	Set   bool
}

// IsSet returns true if OptCreateAdTypeReq was set.
func (o OptCreateAdTypeReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateAdTypeReq) Reset() {
	var v CreateAdTypeReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateAdTypeReq) SetTo(v CreateAdTypeReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateAdTypeReq) Get() (v CreateAdTypeReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateAdTypeReq) Or(d CreateAdTypeReq) CreateAdTypeReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateChannelReq returns new OptCreateChannelReq with value set to v.
func NewOptCreateChannelReq(v CreateChannelReq) OptCreateChannelReq {
	return OptCreateChannelReq{
		Value: v,
		Set:   true,
	}
}

// OptCreateChannelReq is optional CreateChannelReq.
type OptCreateChannelReq struct {
	Value CreateChannelReq
	Set   bool
}

// IsSet returns true if OptCreateChannelReq was set.
func (o OptCreateChannelReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateChannelReq) Reset() {
	var v CreateChannelReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateChannelReq) SetTo(v CreateChannelReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateChannelReq) Get() (v CreateChannelReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateChannelReq) Or(d CreateChannelReq) CreateChannelReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateChannelSiteMapReq returns new OptCreateChannelSiteMapReq with value set to v.
func NewOptCreateChannelSiteMapReq(v CreateChannelSiteMapReq) OptCreateChannelSiteMapReq {
	return OptCreateChannelSiteMapReq{
		Value: v,
		Set:   true,
	}
}

// OptCreateChannelSiteMapReq is optional CreateChannelSiteMapReq.
type OptCreateChannelSiteMapReq struct {
	Value CreateChannelSiteMapReq
	Set   bool
}

// IsSet returns true if OptCreateChannelSiteMapReq was set.
func (o OptCreateChannelSiteMapReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateChannelSiteMapReq) Reset() {
	var v CreateChannelSiteMapReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateChannelSiteMapReq) SetTo(v CreateChannelSiteMapReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateChannelSiteMapReq) Get() (v CreateChannelSiteMapReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateChannelSiteMapReq) Or(d CreateChannelSiteMapReq) CreateChannelSiteMapReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateForChannelAdTypeReq returns new OptCreateForChannelAdTypeReq with value set to v.
func NewOptCreateForChannelAdTypeReq(v CreateForChannelAdTypeReq) OptCreateForChannelAdTypeReq {
	return OptCreateForChannelAdTypeReq{
		Value: v,
		Set:   true,
	}
}

// OptCreateForChannelAdTypeReq is optional CreateForChannelAdTypeReq.
type OptCreateForChannelAdTypeReq struct {
	Value CreateForChannelAdTypeReq
	Set   bool
}

// IsSet returns true if OptCreateForChannelAdTypeReq was set.
func (o OptCreateForChannelAdTypeReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateForChannelAdTypeReq) Reset() {
	var v CreateForChannelAdTypeReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateForChannelAdTypeReq) SetTo(v CreateForChannelAdTypeReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateForChannelAdTypeReq) Get() (v CreateForChannelAdTypeReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateForChannelAdTypeReq) Or(d CreateForChannelAdTypeReq) CreateForChannelAdTypeReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateSiteReq returns new OptCreateSiteReq with value set to v.
func NewOptCreateSiteReq(v CreateSiteReq) OptCreateSiteReq {
	return OptCreateSiteReq{
		Value: v,
		Set:   true,
	}
}

// OptCreateSiteReq is optional CreateSiteReq.
type OptCreateSiteReq struct {
	Value CreateSiteReq
	Set   bool
}

// IsSet returns true if OptCreateSiteReq was set.
func (o OptCreateSiteReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateSiteReq) Reset() {
	var v CreateSiteReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateSiteReq) SetTo(v CreateSiteReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateSiteReq) Get() (v CreateSiteReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateSiteReq) Or(d CreateSiteReq) CreateSiteReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateZoneReq returns new OptCreateZoneReq with value set to v.
func NewOptCreateZoneReq(v CreateZoneReq) OptCreateZoneReq {
	return OptCreateZoneReq{
		Value: v,
		Set:   true,
	}
}

// OptCreateZoneReq is optional CreateZoneReq.
type OptCreateZoneReq struct {
	Value CreateZoneReq
	Set   bool
}

// IsSet returns true if OptCreateZoneReq was set.
func (o OptCreateZoneReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateZoneReq) Reset() {
	var v CreateZoneReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateZoneReq) SetTo(v CreateZoneReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateZoneReq) Get() (v CreateZoneReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateZoneReq) Or(d CreateZoneReq) CreateZoneReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat32 returns new OptFloat32 with value set to v.
func NewOptFloat32(v float32) OptFloat32 {
	return OptFloat32{
		Value: v,
		Set:   true,
	}
}

// OptFloat32 is optional float32.
type OptFloat32 struct {
	Value float32
	Set   bool
}

// IsSet returns true if OptFloat32 was set.
func (o OptFloat32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat32) Reset() {
	var v float32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat32) SetTo(v float32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat32) Get() (v float32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat32) Or(d float32) float32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilBool returns new OptNilBool with value set to v.
func NewOptNilBool(v bool) OptNilBool {
	return OptNilBool{
		Value: v,
		Set:   true,
	}
}

// OptNilBool is optional nullable bool.
type OptNilBool struct {
	Value bool
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilBool was set.
func (o OptNilBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilBool) SetTo(v bool) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsSet returns true if value is Null.
func (o OptNilBool) IsNull() bool { return o.Null }

// SetNull sets value to null.
func (o *OptNilBool) SetToNull() {
	o.Set = true
	o.Null = true
	var v bool
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilBool) Get() (v bool, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilFloat32 returns new OptNilFloat32 with value set to v.
func NewOptNilFloat32(v float32) OptNilFloat32 {
	return OptNilFloat32{
		Value: v,
		Set:   true,
	}
}

// OptNilFloat32 is optional nullable float32.
type OptNilFloat32 struct {
	Value float32
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilFloat32 was set.
func (o OptNilFloat32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilFloat32) Reset() {
	var v float32
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilFloat32) SetTo(v float32) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsSet returns true if value is Null.
func (o OptNilFloat32) IsNull() bool { return o.Null }

// SetNull sets value to null.
func (o *OptNilFloat32) SetToNull() {
	o.Set = true
	o.Null = true
	var v float32
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilFloat32) Get() (v float32, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilFloat32) Or(d float32) float32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilInt32 returns new OptNilInt32 with value set to v.
func NewOptNilInt32(v int32) OptNilInt32 {
	return OptNilInt32{
		Value: v,
		Set:   true,
	}
}

// OptNilInt32 is optional nullable int32.
type OptNilInt32 struct {
	Value int32
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt32 was set.
func (o OptNilInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt32) SetTo(v int32) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsSet returns true if value is Null.
func (o OptNilInt32) IsNull() bool { return o.Null }

// SetNull sets value to null.
func (o *OptNilInt32) SetToNull() {
	o.Set = true
	o.Null = true
	var v int32
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt32) Get() (v int32, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsSet returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateChannelReq returns new OptUpdateChannelReq with value set to v.
func NewOptUpdateChannelReq(v UpdateChannelReq) OptUpdateChannelReq {
	return OptUpdateChannelReq{
		Value: v,
		Set:   true,
	}
}

// OptUpdateChannelReq is optional UpdateChannelReq.
type OptUpdateChannelReq struct {
	Value UpdateChannelReq
	Set   bool
}

// IsSet returns true if OptUpdateChannelReq was set.
func (o OptUpdateChannelReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateChannelReq) Reset() {
	var v UpdateChannelReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateChannelReq) SetTo(v UpdateChannelReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateChannelReq) Get() (v UpdateChannelReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateChannelReq) Or(d UpdateChannelReq) UpdateChannelReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateChannelSiteMapReq returns new OptUpdateChannelSiteMapReq with value set to v.
func NewOptUpdateChannelSiteMapReq(v UpdateChannelSiteMapReq) OptUpdateChannelSiteMapReq {
	return OptUpdateChannelSiteMapReq{
		Value: v,
		Set:   true,
	}
}

// OptUpdateChannelSiteMapReq is optional UpdateChannelSiteMapReq.
type OptUpdateChannelSiteMapReq struct {
	Value UpdateChannelSiteMapReq
	Set   bool
}

// IsSet returns true if OptUpdateChannelSiteMapReq was set.
func (o OptUpdateChannelSiteMapReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateChannelSiteMapReq) Reset() {
	var v UpdateChannelSiteMapReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateChannelSiteMapReq) SetTo(v UpdateChannelSiteMapReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateChannelSiteMapReq) Get() (v UpdateChannelSiteMapReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateChannelSiteMapReq) Or(d UpdateChannelSiteMapReq) UpdateChannelSiteMapReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateSiteReq returns new OptUpdateSiteReq with value set to v.
func NewOptUpdateSiteReq(v UpdateSiteReq) OptUpdateSiteReq {
	return OptUpdateSiteReq{
		Value: v,
		Set:   true,
	}
}

// OptUpdateSiteReq is optional UpdateSiteReq.
type OptUpdateSiteReq struct {
	Value UpdateSiteReq
	Set   bool
}

// IsSet returns true if OptUpdateSiteReq was set.
func (o OptUpdateSiteReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateSiteReq) Reset() {
	var v UpdateSiteReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateSiteReq) SetTo(v UpdateSiteReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateSiteReq) Get() (v UpdateSiteReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateSiteReq) Or(d UpdateSiteReq) UpdateSiteReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateZoneReq returns new OptUpdateZoneReq with value set to v.
func NewOptUpdateZoneReq(v UpdateZoneReq) OptUpdateZoneReq {
	return OptUpdateZoneReq{
		Value: v,
		Set:   true,
	}
}

// OptUpdateZoneReq is optional UpdateZoneReq.
type OptUpdateZoneReq struct {
	Value UpdateZoneReq
	Set   bool
}

// IsSet returns true if OptUpdateZoneReq was set.
func (o OptUpdateZoneReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateZoneReq) Reset() {
	var v UpdateZoneReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateZoneReq) SetTo(v UpdateZoneReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateZoneReq) Get() (v UpdateZoneReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateZoneReq) Or(d UpdateZoneReq) UpdateZoneReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Priority
type Priority struct {
	ChannelId                         OptNilInt32   `json:"ChannelId"`
	FloorPrice                        OptNilFloat32 `json:"FloorPrice"`
	ID                                OptNilInt32   `json:"Id"`
	IsAdChain                         OptBool       `json:"IsAdChain"`
	IsAdChainOptimized                OptBool       `json:"IsAdChainOptimized"`
	IsAdChainOrdered                  OptBool       `json:"IsAdChainOrdered"`
	IsAuction                         OptBool       `json:"IsAuction"`
	IsDeleted                         OptBool       `json:"IsDeleted"`
	IsKeywordOptimized                OptNilBool    `json:"IsKeywordOptimized"`
	IsSecondPricing                   OptNilBool    `json:"IsSecondPricing"`
	Name                              OptString     `json:"Name"`
	PassbackTimeout                   OptNilInt32   `json:"PassbackTimeout"`
	RelevancyScoreConfig              OptNilString  `json:"RelevancyScoreConfig"`
	RelevancyScoreConfigJSON          OptNilString  `json:"RelevancyScoreConfigJSON"`
	SelectionAlgorithm                OptInt32      `json:"SelectionAlgorithm"`
	SerializeRelevancyScoreConfigJSON OptNilBool    `json:"SerializeRelevancyScoreConfigJSON"`
	Weight                            OptNilInt32   `json:"Weight"`
}

// GetChannelId returns the value of ChannelId.
func (s *Priority) GetChannelId() OptNilInt32 {
	return s.ChannelId
}

// GetFloorPrice returns the value of FloorPrice.
func (s *Priority) GetFloorPrice() OptNilFloat32 {
	return s.FloorPrice
}

// GetID returns the value of ID.
func (s *Priority) GetID() OptNilInt32 {
	return s.ID
}

// GetIsAdChain returns the value of IsAdChain.
func (s *Priority) GetIsAdChain() OptBool {
	return s.IsAdChain
}

// GetIsAdChainOptimized returns the value of IsAdChainOptimized.
func (s *Priority) GetIsAdChainOptimized() OptBool {
	return s.IsAdChainOptimized
}

// GetIsAdChainOrdered returns the value of IsAdChainOrdered.
func (s *Priority) GetIsAdChainOrdered() OptBool {
	return s.IsAdChainOrdered
}

// GetIsAuction returns the value of IsAuction.
func (s *Priority) GetIsAuction() OptBool {
	return s.IsAuction
}

// GetIsDeleted returns the value of IsDeleted.
func (s *Priority) GetIsDeleted() OptBool {
	return s.IsDeleted
}

// GetIsKeywordOptimized returns the value of IsKeywordOptimized.
func (s *Priority) GetIsKeywordOptimized() OptNilBool {
	return s.IsKeywordOptimized
}

// GetIsSecondPricing returns the value of IsSecondPricing.
func (s *Priority) GetIsSecondPricing() OptNilBool {
	return s.IsSecondPricing
}

// GetName returns the value of Name.
func (s *Priority) GetName() OptString {
	return s.Name
}

// GetPassbackTimeout returns the value of PassbackTimeout.
func (s *Priority) GetPassbackTimeout() OptNilInt32 {
	return s.PassbackTimeout
}

// GetRelevancyScoreConfig returns the value of RelevancyScoreConfig.
func (s *Priority) GetRelevancyScoreConfig() OptNilString {
	return s.RelevancyScoreConfig
}

// GetRelevancyScoreConfigJSON returns the value of RelevancyScoreConfigJSON.
func (s *Priority) GetRelevancyScoreConfigJSON() OptNilString {
	return s.RelevancyScoreConfigJSON
}

// GetSelectionAlgorithm returns the value of SelectionAlgorithm.
func (s *Priority) GetSelectionAlgorithm() OptInt32 {
	return s.SelectionAlgorithm
}

// GetSerializeRelevancyScoreConfigJSON returns the value of SerializeRelevancyScoreConfigJSON.
func (s *Priority) GetSerializeRelevancyScoreConfigJSON() OptNilBool {
	return s.SerializeRelevancyScoreConfigJSON
}

// GetWeight returns the value of Weight.
func (s *Priority) GetWeight() OptNilInt32 {
	return s.Weight
}

// SetChannelId sets the value of ChannelId.
func (s *Priority) SetChannelId(val OptNilInt32) {
	s.ChannelId = val
}

// SetFloorPrice sets the value of FloorPrice.
func (s *Priority) SetFloorPrice(val OptNilFloat32) {
	s.FloorPrice = val
}

// SetID sets the value of ID.
func (s *Priority) SetID(val OptNilInt32) {
	s.ID = val
}

// SetIsAdChain sets the value of IsAdChain.
func (s *Priority) SetIsAdChain(val OptBool) {
	s.IsAdChain = val
}

// SetIsAdChainOptimized sets the value of IsAdChainOptimized.
func (s *Priority) SetIsAdChainOptimized(val OptBool) {
	s.IsAdChainOptimized = val
}

// SetIsAdChainOrdered sets the value of IsAdChainOrdered.
func (s *Priority) SetIsAdChainOrdered(val OptBool) {
	s.IsAdChainOrdered = val
}

// SetIsAuction sets the value of IsAuction.
func (s *Priority) SetIsAuction(val OptBool) {
	s.IsAuction = val
}

// SetIsDeleted sets the value of IsDeleted.
func (s *Priority) SetIsDeleted(val OptBool) {
	s.IsDeleted = val
}

// SetIsKeywordOptimized sets the value of IsKeywordOptimized.
func (s *Priority) SetIsKeywordOptimized(val OptNilBool) {
	s.IsKeywordOptimized = val
}

// SetIsSecondPricing sets the value of IsSecondPricing.
func (s *Priority) SetIsSecondPricing(val OptNilBool) {
	s.IsSecondPricing = val
}

// SetName sets the value of Name.
func (s *Priority) SetName(val OptString) {
	s.Name = val
}

// SetPassbackTimeout sets the value of PassbackTimeout.
func (s *Priority) SetPassbackTimeout(val OptNilInt32) {
	s.PassbackTimeout = val
}

// SetRelevancyScoreConfig sets the value of RelevancyScoreConfig.
func (s *Priority) SetRelevancyScoreConfig(val OptNilString) {
	s.RelevancyScoreConfig = val
}

// SetRelevancyScoreConfigJSON sets the value of RelevancyScoreConfigJSON.
func (s *Priority) SetRelevancyScoreConfigJSON(val OptNilString) {
	s.RelevancyScoreConfigJSON = val
}

// SetSelectionAlgorithm sets the value of SelectionAlgorithm.
func (s *Priority) SetSelectionAlgorithm(val OptInt32) {
	s.SelectionAlgorithm = val
}

// SetSerializeRelevancyScoreConfigJSON sets the value of SerializeRelevancyScoreConfigJSON.
func (s *Priority) SetSerializeRelevancyScoreConfigJSON(val OptNilBool) {
	s.SerializeRelevancyScoreConfigJSON = val
}

// SetWeight sets the value of Weight.
func (s *Priority) SetWeight(val OptNilInt32) {
	s.Weight = val
}

// Ref: #/components/schemas/Site
type Site struct {
	ID            OptNilInt32   `json:"Id"`
	IsDeleted     OptNilBool    `json:"IsDeleted"`
	NetworkMargin OptNilFloat32 `json:"NetworkMargin"`
	// Deprecated: schema marks this property as deprecated.
	PublisherAccountId OptNilInt32 `json:"PublisherAccountId"`
	Title              OptString   `json:"Title"`
	URL                OptString   `json:"Url"`
}

// GetID returns the value of ID.
func (s *Site) GetID() OptNilInt32 {
	return s.ID
}

// GetIsDeleted returns the value of IsDeleted.
func (s *Site) GetIsDeleted() OptNilBool {
	return s.IsDeleted
}

// GetNetworkMargin returns the value of NetworkMargin.
func (s *Site) GetNetworkMargin() OptNilFloat32 {
	return s.NetworkMargin
}

// GetPublisherAccountId returns the value of PublisherAccountId.
func (s *Site) GetPublisherAccountId() OptNilInt32 {
	return s.PublisherAccountId
}

// GetTitle returns the value of Title.
func (s *Site) GetTitle() OptString {
	return s.Title
}

// GetURL returns the value of URL.
func (s *Site) GetURL() OptString {
	return s.URL
}

// SetID sets the value of ID.
func (s *Site) SetID(val OptNilInt32) {
	s.ID = val
}

// SetIsDeleted sets the value of IsDeleted.
func (s *Site) SetIsDeleted(val OptNilBool) {
	s.IsDeleted = val
}

// SetNetworkMargin sets the value of NetworkMargin.
func (s *Site) SetNetworkMargin(val OptNilFloat32) {
	s.NetworkMargin = val
}

// SetPublisherAccountId sets the value of PublisherAccountId.
func (s *Site) SetPublisherAccountId(val OptNilInt32) {
	s.PublisherAccountId = val
}

// SetTitle sets the value of Title.
func (s *Site) SetTitle(val OptString) {
	s.Title = val
}

// SetURL sets the value of URL.
func (s *Site) SetURL(val OptString) {
	s.URL = val
}

// Ref: #/components/schemas/SiteList
type SiteList struct {
	Items      []Site   `json:"items"`
	Page       OptInt32 `json:"page"`
	PageSize   OptInt32 `json:"pageSize"`
	TotalItems OptInt64 `json:"totalItems"`
	TotalPages OptInt32 `json:"totalPages"`
}

// GetItems returns the value of Items.
func (s *SiteList) GetItems() []Site {
	return s.Items
}

// GetPage returns the value of Page.
func (s *SiteList) GetPage() OptInt32 {
	return s.Page
}

// GetPageSize returns the value of PageSize.
func (s *SiteList) GetPageSize() OptInt32 {
	return s.PageSize
}

// GetTotalItems returns the value of TotalItems.
func (s *SiteList) GetTotalItems() OptInt64 {
	return s.TotalItems
}

// GetTotalPages returns the value of TotalPages.
func (s *SiteList) GetTotalPages() OptInt32 {
	return s.TotalPages
}

// SetItems sets the value of Items.
func (s *SiteList) SetItems(val []Site) {
	s.Items = val
}

// SetPage sets the value of Page.
func (s *SiteList) SetPage(val OptInt32) {
	s.Page = val
}

// SetPageSize sets the value of PageSize.
func (s *SiteList) SetPageSize(val OptInt32) {
	s.PageSize = val
}

// SetTotalItems sets the value of TotalItems.
func (s *SiteList) SetTotalItems(val OptInt64) {
	s.TotalItems = val
}

// SetTotalPages sets the value of TotalPages.
func (s *SiteList) SetTotalPages(val OptInt32) {
	s.TotalPages = val
}

type UpdateChannelReq struct {
	AdTypes []int32 `json:"AdTypes"`
	Engine  int32   `json:"Engine"`
	ID      int32   `json:"Id"`
	Title   string  `json:"Title"`
}

// GetAdTypes returns the value of AdTypes.
func (s *UpdateChannelReq) GetAdTypes() []int32 {
	return s.AdTypes
}

// GetEngine returns the value of Engine.
func (s *UpdateChannelReq) GetEngine() int32 {
	return s.Engine
}

// GetID returns the value of ID.
func (s *UpdateChannelReq) GetID() int32 {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *UpdateChannelReq) GetTitle() string {
	return s.Title
}

// SetAdTypes sets the value of AdTypes.
func (s *UpdateChannelReq) SetAdTypes(val []int32) {
	s.AdTypes = val
}

// SetEngine sets the value of Engine.
func (s *UpdateChannelReq) SetEngine(val int32) {
	s.Engine = val
}

// SetID sets the value of ID.
func (s *UpdateChannelReq) SetID(val int32) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *UpdateChannelReq) SetTitle(val string) {
	s.Title = val
}

type UpdateChannelSiteMapReq struct {
	ChannelId int32 `json:"channelId"`
	Priority  int32 `json:"priority"`
	SiteId    int32 `json:"siteId"`
}

// GetChannelId returns the value of ChannelId.
func (s *UpdateChannelSiteMapReq) GetChannelId() int32 {
	return s.ChannelId
}

// GetPriority returns the value of Priority.
func (s *UpdateChannelSiteMapReq) GetPriority() int32 {
	return s.Priority
}

// GetSiteId returns the value of SiteId.
func (s *UpdateChannelSiteMapReq) GetSiteId() int32 {
	return s.SiteId
}

// SetChannelId sets the value of ChannelId.
func (s *UpdateChannelSiteMapReq) SetChannelId(val int32) {
	s.ChannelId = val
}

// SetPriority sets the value of Priority.
func (s *UpdateChannelSiteMapReq) SetPriority(val int32) {
	s.Priority = val
}

// SetSiteId sets the value of SiteId.
func (s *UpdateChannelSiteMapReq) SetSiteId(val int32) {
	s.SiteId = val
}

type UpdateSiteReq struct {
	ID            int32         `json:"Id"`
	IsDeleted     OptNilBool    `json:"IsDeleted"`
	NetworkMargin OptNilFloat32 `json:"NetworkMargin"`
	Title         string        `json:"Title"`
	URL           url.URL       `json:"URL"`
}

// GetID returns the value of ID.
func (s *UpdateSiteReq) GetID() int32 {
	return s.ID
}

// GetIsDeleted returns the value of IsDeleted.
func (s *UpdateSiteReq) GetIsDeleted() OptNilBool {
	return s.IsDeleted
}

// GetNetworkMargin returns the value of NetworkMargin.
func (s *UpdateSiteReq) GetNetworkMargin() OptNilFloat32 {
	return s.NetworkMargin
}

// GetTitle returns the value of Title.
func (s *UpdateSiteReq) GetTitle() string {
	return s.Title
}

// GetURL returns the value of URL.
func (s *UpdateSiteReq) GetURL() url.URL {
	return s.URL
}

// SetID sets the value of ID.
func (s *UpdateSiteReq) SetID(val int32) {
	s.ID = val
}

// SetIsDeleted sets the value of IsDeleted.
func (s *UpdateSiteReq) SetIsDeleted(val OptNilBool) {
	s.IsDeleted = val
}

// SetNetworkMargin sets the value of NetworkMargin.
func (s *UpdateSiteReq) SetNetworkMargin(val OptNilFloat32) {
	s.NetworkMargin = val
}

// SetTitle sets the value of Title.
func (s *UpdateSiteReq) SetTitle(val string) {
	s.Title = val
}

// SetURL sets the value of URL.
func (s *UpdateSiteReq) SetURL(val url.URL) {
	s.URL = val
}

type UpdateZoneReq struct {
	ID        int32       `json:"Id"`
	IsDeleted OptNilBool  `json:"IsDeleted"`
	Name      string      `json:"Name"`
	SiteId    OptNilInt32 `json:"SiteId"`
}

// GetID returns the value of ID.
func (s *UpdateZoneReq) GetID() int32 {
	return s.ID
}

// GetIsDeleted returns the value of IsDeleted.
func (s *UpdateZoneReq) GetIsDeleted() OptNilBool {
	return s.IsDeleted
}

// GetName returns the value of Name.
func (s *UpdateZoneReq) GetName() string {
	return s.Name
}

// GetSiteId returns the value of SiteId.
func (s *UpdateZoneReq) GetSiteId() OptNilInt32 {
	return s.SiteId
}

// SetID sets the value of ID.
func (s *UpdateZoneReq) SetID(val int32) {
	s.ID = val
}

// SetIsDeleted sets the value of IsDeleted.
func (s *UpdateZoneReq) SetIsDeleted(val OptNilBool) {
	s.IsDeleted = val
}

// SetName sets the value of Name.
func (s *UpdateZoneReq) SetName(val string) {
	s.Name = val
}

// SetSiteId sets the value of SiteId.
func (s *UpdateZoneReq) SetSiteId(val OptNilInt32) {
	s.SiteId = val
}

// Ref: #/components/schemas/Zone
type Zone struct {
	ID        OptNilInt32 `json:"Id"`
	IsDeleted OptNilBool  `json:"IsDeleted"`
	Name      OptString   `json:"Name"`
	SiteId    OptInt32    `json:"SiteId"`
}

// GetID returns the value of ID.
func (s *Zone) GetID() OptNilInt32 {
	return s.ID
}

// GetIsDeleted returns the value of IsDeleted.
func (s *Zone) GetIsDeleted() OptNilBool {
	return s.IsDeleted
}

// GetName returns the value of Name.
func (s *Zone) GetName() OptString {
	return s.Name
}

// GetSiteId returns the value of SiteId.
func (s *Zone) GetSiteId() OptInt32 {
	return s.SiteId
}

// SetID sets the value of ID.
func (s *Zone) SetID(val OptNilInt32) {
	s.ID = val
}

// SetIsDeleted sets the value of IsDeleted.
func (s *Zone) SetIsDeleted(val OptNilBool) {
	s.IsDeleted = val
}

// SetName sets the value of Name.
func (s *Zone) SetName(val OptString) {
	s.Name = val
}

// SetSiteId sets the value of SiteId.
func (s *Zone) SetSiteId(val OptInt32) {
	s.SiteId = val
}

// Ref: #/components/schemas/ZoneList
type ZoneList struct {
	Items      []Zone   `json:"items"`
	Page       OptInt32 `json:"page"`
	PageSize   OptInt32 `json:"pageSize"`
	TotalItems OptInt64 `json:"totalItems"`
	TotalPages OptInt32 `json:"totalPages"`
}

// GetItems returns the value of Items.
func (s *ZoneList) GetItems() []Zone {
	return s.Items
}

// GetPage returns the value of Page.
func (s *ZoneList) GetPage() OptInt32 {
	return s.Page
}

// GetPageSize returns the value of PageSize.
func (s *ZoneList) GetPageSize() OptInt32 {
	return s.PageSize
}

// GetTotalItems returns the value of TotalItems.
func (s *ZoneList) GetTotalItems() OptInt64 {
	return s.TotalItems
}

// GetTotalPages returns the value of TotalPages.
func (s *ZoneList) GetTotalPages() OptInt32 {
	return s.TotalPages
}

// SetItems sets the value of Items.
func (s *ZoneList) SetItems(val []Zone) {
	s.Items = val
}

// SetPage sets the value of Page.
func (s *ZoneList) SetPage(val OptInt32) {
	s.Page = val
}

// SetPageSize sets the value of PageSize.
func (s *ZoneList) SetPageSize(val OptInt32) {
	s.PageSize = val
}

// SetTotalItems sets the value of TotalItems.
func (s *ZoneList) SetTotalItems(val OptInt64) {
	s.TotalItems = val
}

// SetTotalPages sets the value of TotalPages.
func (s *ZoneList) SetTotalPages(val OptInt32) {
	s.TotalPages = val
}
