// Code generated by ogen, DO NOT EDIT.

package client

// setDefaults set default value of fields.
func (s *Channel) setDefaults() {
	{
		val := float32(0)
		s.CPM.SetTo(val)
	}
	{
		val := string("0")
		s.Engine.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateChannelReq) setDefaults() {
	{
		val := int32(0)
		s.Engine = val
	}
	{
		val := bool(false)
		s.IsDeleted.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateSiteReq) setDefaults() {
	{
		val := bool(false)
		s.IsDeleted.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateZoneReq) setDefaults() {
	{
		val := bool(false)
		s.IsDeleted.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UpdateChannelReq) setDefaults() {
	{
		val := int32(0)
		s.Engine = val
	}
}

// setDefaults set default value of fields.
func (s *UpdateSiteReq) setDefaults() {
	{
		val := bool(false)
		s.IsDeleted.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UpdateZoneReq) setDefaults() {
	{
		val := bool(false)
		s.IsDeleted.SetTo(val)
	}
}
